In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\visha\OneDrive\Data Analytics\pandas_project_dataset_500_rows.csv")
df

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date
0,1001,Amit,Watch,Fashion,4,4500,Hyderabad,2025-08-14
1,1002,Sneha,Phone,Electronics,1,25000,Delhi,2025-10-19
2,1003,Ravi,Watch,Fashion,5,4500,Bangalore,2025-01-16
3,1004,Priya,Chair,Furniture,4,3500,Mumbai,2025-06-28
4,1005,Kiran,Laptop,Electronics,3,55000,Delhi,2025-11-11
...,...,...,...,...,...,...,...,...
495,1496,Arjun,Book,Books,5,500,Pune,2025-06-11
496,1497,Neha,Watch,Fashion,2,4500,Delhi,2025-09-07
497,1498,Neha,Book,Books,3,500,Chennai,2025-06-08
498,1499,Kiran,Watch,Fashion,5,4500,Bangalore,2025-09-11
499,1500,Kiran,Book,Books,2,500,Mumbai,2025-10-20

In [4]:
df.head(10)

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date
0,1001,Amit,Watch,Fashion,4,4500,Hyderabad,2025-08-14
1,1002,Sneha,Phone,Electronics,1,25000,Delhi,2025-10-19
2,1003,Ravi,Watch,Fashion,5,4500,Bangalore,2025-01-16
3,1004,Priya,Chair,Furniture,4,3500,Mumbai,2025-06-28
4,1005,Kiran,Laptop,Electronics,3,55000,Delhi,2025-11-11
5,1006,Neha,Watch,Fashion,2,4500,Pune,2025-11-14
6,1007,Arjun,Book,Books,3,500,Chennai,2025-09-07
7,1008,Priya,Watch,Fashion,2,4500,Mumbai,2025-03-13
8,1009,Vishal,Phone,Electronics,4,25000,Delhi,2025-11-25
9,1010,Ravi,Headphones,Electronics,1,2000,Hyderabad,2025-01-23

In [5]:
#no of rows
df.shape[0]

500

In [6]:
#no of columns
df.shape[1]

8

In [7]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'City', 'Order_Date'],
      dtype='object')

In [8]:
df.dtypes

Order_ID          int64
Customer_Name    object
Product          object
Category         object
Quantity          int64
Unit_Price        int64
City             object
Order_Date       object
dtype: object

In [9]:
df.isnull().sum()

Order_ID         0
Customer_Name    0
Product          0
Category         0
Quantity         0
Unit_Price       0
City             0
Order_Date       0
dtype: int64

In [11]:
df[['Customer_Name','Product','Quantity','Unit_Price']]

    Customer_Name Product  Quantity  Unit_Price
0            Amit   Watch         4        4500
1           Sneha   Phone         1       25000
2            Ravi   Watch         5        4500
3           Priya   Chair         4        3500
4           Kiran  Laptop         3       55000
..            ...     ...       ...         ...
495         Arjun    Book         5         500
496          Neha   Watch         2        4500
497          Neha    Book         3         500
498         Kiran   Watch         5        4500
499         Kiran    Book         2         500

[500 rows x 4 columns]

In [12]:
df.groupby('Product')['Quantity'].sum()

Product
Book          193
Chair         194
Headphones    187
Laptop        188
Phone         186
Shoes         136
Table         180
Watch         229
Name: Quantity, dtype: int64

In [16]:
df.groupby('Category')['Unit_Price'].mean()

Category
Books            500.000000
Electronics    27771.739130
Fashion         3438.461538
Furniture       4244.274809
Name: Unit_Price, dtype: float64

In [18]:
df[(df['Quantity'] > 3) & (df['Unit_Price'] > 5000)]

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date
8,1009,Vishal,Phone,Electronics,4,25000,Delhi,2025-11-25
10,1011,Kiran,Phone,Electronics,4,25000,Chennai,2025-11-27
13,1014,Kiran,Laptop,Electronics,5,55000,Mumbai,2025-01-31
17,1018,Priya,Phone,Electronics,4,25000,Chennai,2025-09-13
37,1038,Vishal,Phone,Electronics,4,25000,Mumbai,2025-08-16
57,1058,Amit,Phone,Electronics,5,25000,Pune,2025-03-10
68,1069,Ravi,Phone,Electronics,4,25000,Hyderabad,2025-02-11
75,1076,Ravi,Laptop,Electronics,5,55000,Chennai,2025-11-26
88,1089,Kiran,Laptop,Electronics,5,55000,Hyderabad,2025-06-14
91,1092,Rahul,Phone,Electronics,5,25000,Bangalore,2025-01-27
110,1111,Rahul,Laptop,Electronics,4,55000,Hyderabad,2025-07-27
121,1122,Amit,Phone,Electronics,5,25000,Bangalore,2025-02-20
122,1123,Arjun,Phone,Electronics,4,25000,Mumbai,2025-11-05
130,1131,Rahul,Phone,Electronics,4,25000,Pune,2025-01-18
167,1168,Arjun,Laptop,Electronics,4,55000,Pune,2025-10-25
181,1182,Kiran,Phone,Electronics,5,25000,Chennai,2025-01-31
184,1185,Neha,Laptop,Electronics,5,55000,Bangalore,2025-07-24
190,1191,Sneha,Phone,Electronics,4,25000,Hyderabad,2025-03-27
196,1197,Rahul,Laptop,Electronics,5,55000,Delhi,2025-11-12
210,1211,Kiran,Laptop,Electronics,5,55000,Mumbai,2025-04-11
211,1212,Anjali,Laptop,Electronics,4,55000,Hyderabad,2025-01-08
213,1214,Neha,Laptop,Electronics,5,55000,Pune,2025-05-06
219,1220,Ravi,Laptop,Electronics,4,55000,Chennai,2025-12-29
227,1228,Ravi,Laptop,Electronics,5,55000,Pune,2025-05-17
234,1235,Sneha,Laptop,Electronics,5,55000,Mumbai,2025-12-13
236,1237,Arjun,Laptop,Electronics,5,55000,Hyderabad,2025-10-22
239,1240,Amit,Phone,Electronics,4,25000,Mumbai,2025-07-09
255,1256,Ravi,Laptop,Electronics,4,55000,Mumbai,2025-01-09
271,1272,Ravi,Phone,Electronics,4,25000,Chennai,2025-06-08
283,1284,Ravi,Phone,Electronics,4,25000,Hyderabad,2025-11-16
288,1289,Sneha,Laptop,Electronics,4,55000,Pune,2025-04-14
293,1294,Neha,Phone,Electronics,5,25000,Mumbai,2025-10-16
316,1317,Rahul,Phone,Electronics,5,25000,Bangalore,2025-06-26
355,1356,Neha,Phone,Electronics,5,25000,Chennai,2025-07-19
363,1364,Rahul,Phone,Electronics,5,25000,Delhi,2025-09-28
386,1387,Anjali,Phone,Electronics,4,25000,Pune,2025-02-18
389,1390,Priya,Phone,Electronics,5,25000,Hyderabad,2025-05-28
395,1396,Priya,Phone,Electronics,5,25000,Pune,2025-11-29
397,1398,Amit,Laptop,Electronics,5,55000,Bangalore,2025-04-16
413,1414,Neha,Laptop,Electronics,5,55000,Pune,2025-03-06
431,1432,Sneha,Laptop,Electronics,5,55000,Chennai,2025-09-14
446,1447,Neha,Phone,Electronics,5,25000,Delhi,2025-03-30
472,1473,Anjali,Phone,Electronics,5,25000,Mumbai,2025-08-07
480,1481,Priya,Laptop,Electronics,5,55000,Chennai,2025-07-18
484,1485,Kiran,Laptop,Electronics,5,55000,Pune,2025-10-26
488,1489,Sneha,Laptop,Electronics,5,55000,Delhi,2025-11-29

In [19]:
df.sort_values(by='Unit_Price',ascending=False)

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date
167,1168,Arjun,Laptop,Electronics,4,55000,Pune,2025-10-25
454,1455,Rahul,Laptop,Electronics,1,55000,Bangalore,2025-02-14
337,1338,Kiran,Laptop,Electronics,3,55000,Hyderabad,2025-05-23
451,1452,Kiran,Laptop,Electronics,1,55000,Pune,2025-05-10
358,1359,Arjun,Laptop,Electronics,3,55000,Pune,2025-08-03
...,...,...,...,...,...,...,...,...
361,1362,Arjun,Book,Books,4,500,Chennai,2025-12-31
117,1118,Vishal,Book,Books,5,500,Hyderabad,2025-03-18
120,1121,Anjali,Book,Books,5,500,Bangalore,2025-10-13
351,1352,Vishal,Book,Books,4,500,Hyderabad,2025-09-26
499,1500,Kiran,Book,Books,2,500,Mumbai,2025-10-20

In [43]:
df['City'].value_counts().head(5)

City
Hyderabad    90
Bangalore    88
Pune         83
Delhi        81
Mumbai       79
Name: count, dtype: int64

In [44]:
df.assign(Total_Amount=df['Quantity'] * df['Unit_Price'])

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date,Total_Amount
0,1001,Amit,Watch,Fashion,4,4500,Hyderabad,2025-08-14,18000
1,1002,Sneha,Phone,Electronics,1,25000,Delhi,2025-10-19,25000
2,1003,Ravi,Watch,Fashion,5,4500,Bangalore,2025-01-16,22500
3,1004,Priya,Chair,Furniture,4,3500,Mumbai,2025-06-28,14000
4,1005,Kiran,Laptop,Electronics,3,55000,Delhi,2025-11-11,165000
...,...,...,...,...,...,...,...,...,...
495,1496,Arjun,Book,Books,5,500,Pune,2025-06-11,2500
496,1497,Neha,Watch,Fashion,2,4500,Delhi,2025-09-07,9000
497,1498,Neha,Book,Books,3,500,Chennai,2025-06-08,1500
498,1499,Kiran,Watch,Fashion,5,4500,Bangalore,2025-09-11,22500
499,1500,Kiran,Book,Books,2,500,Mumbai,2025-10-20,1000

In [28]:
df.groupby('City')['Total_Amount'].sum()

City
Bangalore    2480400
Chennai      2961900
Delhi        2670200
Hyderabad    3403300
Mumbai       3196900
Pune         3602100
Name: Total_Amount, dtype: int64

In [30]:
df.pivot_table(values='Total_Amount',index='Category',columns='City',aggfunc='sum')

City         Bangalore  Chennai    Delhi  Hyderabad   Mumbai     Pune
Category
Books            16500    29500    14500      15000    10000    11000
Electronics    1907000  2642000  2133000    2736000  2798000  3148000
Fashion         284400   108900   205200     316800   135900   224100
Furniture       272500   181500   317500     335500   253000   219000

In [49]:
df.loc[df['Unit_Price'].idxmax()]

Order_ID                1005
Customer_Name          Kiran
Product               Laptop
Category         Electronics
Quantity                   3
Unit_Price             55000
City                   Delhi
Order_Date        2025-11-11
Total_Amount          165000
Name: 4, dtype: object

In [50]:
df.loc[df['Unit_Price'].idxmin()]

Order_ID               1007
Customer_Name         Arjun
Product                Book
Category              Books
Quantity                  3
Unit_Price              500
City                Chennai
Order_Date       2025-09-07
Total_Amount           1500
Name: 6, dtype: object

In [51]:
df.nlargest(10,'Total_Amount')

,Order_ID,Customer_Name,Product,Category,Quantity,Unit_Price,City,Order_Date,Total_Amount
13,1014,Kiran,Laptop,Electronics,5,55000,Mumbai,2025-01-31,275000
75,1076,Ravi,Laptop,Electronics,5,55000,Chennai,2025-11-26,275000
88,1089,Kiran,Laptop,Electronics,5,55000,Hyderabad,2025-06-14,275000
184,1185,Neha,Laptop,Electronics,5,55000,Bangalore,2025-07-24,275000
196,1197,Rahul,Laptop,Electronics,5,55000,Delhi,2025-11-12,275000
210,1211,Kiran,Laptop,Electronics,5,55000,Mumbai,2025-04-11,275000
213,1214,Neha,Laptop,Electronics,5,55000,Pune,2025-05-06,275000
227,1228,Ravi,Laptop,Electronics,5,55000,Pune,2025-05-17,275000
234,1235,Sneha,Laptop,Electronics,5,55000,Mumbai,2025-12-13,275000
236,1237,Arjun,Laptop,Electronics,5,55000,Hyderabad,2025-10-22,275000

## Business Insights


1.Which city has the highest total sales
Answer : Pune
2.Which city has the lowest total sales?
Answer : Bangalore 
3.Which product was ordered the most?
Answer : Watch
4.Which product generated the highest revenue?
Answer : Laptop
5.Which category generated the highest revenue?
Answer : Electronics
6.Which category sold the highest quantity of products?
Answer : Electronics
7.Which customer placed the highest number of orders?
Answer : Rahul
8. Which customer spent the most money?
Answer : Kiran
9. What is the average order value?
Answer : 36629.6
10. What is the total revenue generated from all orders?
Answer : 18314800